// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddNode(arg1:main.NodeInfo):Promise<void>;

export function CloseConnection(arg1:string):Promise<void>;

export function Connect(arg1:string):Promise<string>;

export function DeleteNode(arg1:string):Promise<void>;

export function GetNodeInfo(arg1:string):Promise<string>;

export function GetNodes(arg1:string):Promise<Array<main.Node>>;

export function SetWatcherForSelectedNode(arg1:string):Promise<void>;
