// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNodeInfo(arg1) {
  return window['go']['main']['App']['GetNodeInfo'](arg1);
}

export function GetNodes(arg1) {
  return window['go']['main']['App']['GetNodes'](arg1);
}

export function SetWatcherForSelectedNode(arg1) {
  return window['go']['main']['App']['SetWatcherForSelectedNode'](arg1);
}
