// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteConnection(arg1) {
  return window['go']['connection']['ConnectionManager']['DeleteConnection'](arg1);
}

export function GetConnections() {
  return window['go']['connection']['ConnectionManager']['GetConnections']();
}

export function LoadConfig() {
  return window['go']['connection']['ConnectionManager']['LoadConfig']();
}

export function SaveConnection(arg1) {
  return window['go']['connection']['ConnectionManager']['SaveConnection'](arg1);
}
