// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetConnections():Promise<{[key: string]: config.Connection}>;

export function LoadConfig():Promise<void>;

export function SaveConnection(arg1:config.Connection):Promise<void>;
