// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {connection} from '../models';
import {config} from '../models';

export function DeleteConnection(arg1:string):Promise<void>;

export function GetConnections():Promise<Array<connection.ConnectionInfo>>;

export function LoadConfig():Promise<void>;

export function SaveConnection(arg1:config.Connection):Promise<void>;
